name: innvitee_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: 

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon_app.png"

  flutter_native_splash:
  color: "#492E8D"
  image: assets/images/splash_app.png

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/